version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app/src
      - ./backend/server.js:/app/server.js
    env_file:
      - ./.env
  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./.env
